using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;

namespace NTI.iMeter.ComponentStandard.Runtime.Condition
{
    /// <summary>
    /// Factory base for condition runtime component
    /// </summary>
    public abstract class ConditionRuntimeComponentFactoryBase : RuntimeComponentFactoryBase
    {
        /// <summary>
        /// Create a runtime with system built-in data type.
        /// </summary>
        /// <param name="setting">Setting generated by UI component</param>
        /// <param name="dataType">Data type. StrongCustomizedType will not be used.</param>
        /// <returns>Condition runtime</returns>
        public abstract ConditionRuntimeComponentBase CreateRuntime(XmlDocument setting, DataType dataType);
        /// <summary>
        /// Create a runtime with strong customized type.
        /// </summary>
        /// <param name="setting">Setting generated by UI component</param>
        /// <param name="strongCustomizedTypeTypeId">Type id of the strong customized type specified</param>
        /// <returns>Condition runtime</returns>
        public abstract ConditionRuntimeComponentBase CreateRuntime(XmlDocument setting, Guid strongCustomizedTypeTypeId);

        public sealed override ComponentType ComponentType => ComponentType.Condition;
    }
}
