using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;

namespace NTI.iMeter.ComponentStandard.Runtime.Converter
{
    /// <summary>
    /// Factory base for converter runtime component
    /// </summary>
    public abstract class ConverterRuntimeComponentFactoryBase : RuntimeComponentFactoryBase
    {
        /// <summary>
        /// Create a runtime with system built-in data type.
        /// </summary>
        /// <param name="setting">Setting generated by UI component</param>
        /// <param name="dataType">Data type. StrongCustomizedType will not be used.</param>
        /// <param name="outputId">Id of selected output</param>
        /// <returns>Converter runtime</returns>
        public abstract ConverterRuntimeComponentBase CreateRuntime(XmlDocument setting, DataType dataType, Guid outputId);

        /// <summary>
        /// Create a runtime with strong customized type.
        /// </summary>
        /// <param name="setting">Setting generated by UI component</param>
        /// <param name="strongCustomizedTypeTypeId">Type id of the strong customized type specified</param>
        /// <param name="outputId">Id of selected output</param>
        /// <returns>Converter runtime</returns>
        public abstract ConverterRuntimeComponentBase CreateRuntime(XmlDocument setting, Guid strongCustomizedTypeTypeId, Guid outputId);

        public sealed override ComponentType ComponentType => ComponentType.Converter;
    }
}
