using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;

namespace NTI.iMeter.ComponentStandard.Runtime.StrongCustomizedType
{
    /// <summary>
    /// Factory base for strong customized type runtime component
    /// </summary>
    public abstract class StrongCustomizedTypeRuntimeComponentFactoryBase : RuntimeComponentFactoryBase
    {
        /// <summary>
        /// Create a runtime.
        /// </summary>
        /// <param name="setting">Setting generated by UI component</param>
        /// <returns>Strong customized type runtime</returns>
        public abstract StrongCustomizedTypeRuntimeComponentBase CreateRuntime(XmlDocument setting);

        public sealed override ComponentType ComponentType => ComponentType.StrongCustomizedType;
    }
}
