//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTI.iMeter.InternetTransferringEntities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NTI.iMeter.InternetTransferringEntities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Data Package:\nText: {21}\n\nId: {0}\nBatchId: {1}\nCaptureStarted: {2:F}\nCaptureEnded: {3:F}\nCrawlerName: {4}\nCrawlerClientName: {5}\nCrawlerHostId: {6}\nWeaverWave: {7}\nTrustedTime: {8:F}\nTrustedTimeSourceExpandedVariableId: {9}\nTrustedTimeSourceExpandedVariablePath: {10}\nLocalTimeOffesetTick: {11}\nDatabaseValuePackageId: {12}\nDataType: {13}\nStrongCustomizedTypeTypeId: {14}\nExpandedPath: {15}\nExpandedIdPath: {16}\nExpandedVariableId: {17}\nProcessorId: {18}\nProcessorOutputId: {19}\nProc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FormatAlertDataPackage {
            get {
                return ResourceManager.GetString("FormatAlertDataPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (DateTime) {0:F}.
        /// </summary>
        internal static string FormatSerializedDateTime {
            get {
                return ResourceManager.GetString("FormatSerializedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Decimal) {0}.
        /// </summary>
        internal static string FormatSerializedDecimal {
            get {
                return ResourceManager.GetString("FormatSerializedDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Integer) {0}.
        /// </summary>
        internal static string FormatSerializedInteger {
            get {
                return ResourceManager.GetString("FormatSerializedInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (String) {0}.
        /// </summary>
        internal static string FormatSerializedString {
            get {
                return ResourceManager.GetString("FormatSerializedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (StrongCustomizedType in String) {0}.
        /// </summary>
        internal static string FormatSerializedStrongCustomizedTypeInString {
            get {
                return ResourceManager.GetString("FormatSerializedStrongCustomizedTypeInString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UnsignedInteger) {0}.
        /// </summary>
        internal static string FormatSerializedUnsignedInteger {
            get {
                return ResourceManager.GetString("FormatSerializedUnsignedInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Boolean) False.
        /// </summary>
        internal static string ValueSerializedBooleanFalse {
            get {
                return ResourceManager.GetString("ValueSerializedBooleanFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Boolean) True.
        /// </summary>
        internal static string ValueSerializedBooleanTrue {
            get {
                return ResourceManager.GetString("ValueSerializedBooleanTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (StrongCustomizedType) &lt;Empty&gt;.
        /// </summary>
        internal static string ValueSerializedStrongCustomizedTypeEmpty {
            get {
                return ResourceManager.GetString("ValueSerializedStrongCustomizedTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (StrongCustomizedType in Byte Array) &lt;Raw Data&gt;.
        /// </summary>
        internal static string ValueSerializedStrongCustomizedTypeInByteArray {
            get {
                return ResourceManager.GetString("ValueSerializedStrongCustomizedTypeInByteArray", resourceCulture);
            }
        }
    }
}
